[package]
name = "anagram"
version = "0.1.0"
edition = "2021"
description = "Given two strings s and t, return true if t is an anagram of s, and false otherwise." 
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
